// Code generated by "enumer -type=QueryType -trimprefix=QueryType -transform=snake-upper -json -sql -values"; DO NOT EDIT.

package enums

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _QueryTypeName = "FULLHOSTDOMAINPATHMIXED"

var _QueryTypeIndex = [...]uint8{0, 4, 8, 14, 18, 23}

const _QueryTypeLowerName = "fullhostdomainpathmixed"

func (i QueryType) String() string {
	if i < 0 || i >= QueryType(len(_QueryTypeIndex)-1) {
		return fmt.Sprintf("QueryType(%d)", i)
	}
	return _QueryTypeName[_QueryTypeIndex[i]:_QueryTypeIndex[i+1]]
}

func (QueryType) Values() []string {
	return QueryTypeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _QueryTypeNoOp() {
	var x [1]struct{}
	_ = x[QueryTypeFull-(0)]
	_ = x[QueryTypeHost-(1)]
	_ = x[QueryTypeDomain-(2)]
	_ = x[QueryTypePath-(3)]
	_ = x[QueryTypeMixed-(4)]
}

var _QueryTypeValues = []QueryType{QueryTypeFull, QueryTypeHost, QueryTypeDomain, QueryTypePath, QueryTypeMixed}

var _QueryTypeNameToValueMap = map[string]QueryType{
	_QueryTypeName[0:4]:        QueryTypeFull,
	_QueryTypeLowerName[0:4]:   QueryTypeFull,
	_QueryTypeName[4:8]:        QueryTypeHost,
	_QueryTypeLowerName[4:8]:   QueryTypeHost,
	_QueryTypeName[8:14]:       QueryTypeDomain,
	_QueryTypeLowerName[8:14]:  QueryTypeDomain,
	_QueryTypeName[14:18]:      QueryTypePath,
	_QueryTypeLowerName[14:18]: QueryTypePath,
	_QueryTypeName[18:23]:      QueryTypeMixed,
	_QueryTypeLowerName[18:23]: QueryTypeMixed,
}

var _QueryTypeNames = []string{
	_QueryTypeName[0:4],
	_QueryTypeName[4:8],
	_QueryTypeName[8:14],
	_QueryTypeName[14:18],
	_QueryTypeName[18:23],
}

// QueryTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func QueryTypeString(s string) (QueryType, error) {
	if val, ok := _QueryTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _QueryTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to QueryType values", s)
}

// QueryTypeValues returns all values of the enum
func QueryTypeValues() []QueryType {
	return _QueryTypeValues
}

// QueryTypeStrings returns a slice of all String values of the enum
func QueryTypeStrings() []string {
	strs := make([]string, len(_QueryTypeNames))
	copy(strs, _QueryTypeNames)
	return strs
}

// IsAQueryType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i QueryType) IsAQueryType() bool {
	for _, v := range _QueryTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for QueryType
func (i QueryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for QueryType
func (i *QueryType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("QueryType should be a string, got %s", data)
	}

	var err error
	*i, err = QueryTypeString(s)
	return err
}

func (i QueryType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *QueryType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of QueryType: %[1]T(%[1]v)", value)
	}

	val, err := QueryTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
